---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecret.name }}
  labels:
{{ include "helm.labels" . | indent 4 }}
type: Opaque
data:
{{- ( include "ailefroide.secret" . ) | indent 2 -}}
